/**
 * Maps Odds API team names → ESPN team abbreviations, keyed by Odds API sport key.
 *
 * Used for exact-match event correlation in findEspnMatch(), bypassing fuzzy string
 * comparison for sports with a fixed, finite set of teams.
 *
 * Coverage: basketball_nba, soccer_epl, soccer_spain_la_liga, soccer_germany_bundesliga,
 *           soccer_italy_serie_a, soccer_italy_coppa_italia, soccer_netherlands_eredivisie,
 *           soccer_france_ligue_one, soccer_brazil_campeonato,
 *           icehockey_nhl, soccer_uefa_champs_league, soccer_conmebol_copa_libertadores (partial),
 *           soccer_fifa_world_cup (partial — only teams with known Odds API ↔ ESPN name divergence).
 *
 * Multiple Odds API name variants for the same team are included as separate keys.
 * Abbreviations verified against live ESPN scoreboard API responses — March 2026.
 */

/**
 * Odds API name → corrected name used by ESPN as displayName.
 * Applied before fuzzy matching to fix structural name divergence that similarity scoring
 * can't bridge (e.g. "Sporting Lisbon" ↔ "Sporting CP", "USA" ↔ "United States").
 */
export const TEAM_NAME_CORRECTIONS: Record<string, string> = {
  // Soccer club name divergence
  "Sporting Lisbon": "Sporting CP",
  // National team name divergence (Odds API abbreviation vs ESPN full name)
  "USA": "United States",
  "Czech Republic": "Czechia",
  "DR Congo": "Congo DR",
  // MMA fighter name divergence (nickname vs legal name, full name vs shortened)
  "Lupita Godinez": "Loopy Godínez",
  "Paulo Henrique Costa": "Paulo Costa",
};
export const ODDS_TO_ESPN_ABBREV: Record<string, Record<string, string>> = {
  basketball_nba: {
    "Atlanta Hawks": "ATL",
    "Boston Celtics": "BOS",
    "Brooklyn Nets": "BKN",
    "Charlotte Hornets": "CHA",
    "Chicago Bulls": "CHI",
    "Cleveland Cavaliers": "CLE",
    "Dallas Mavericks": "DAL",
    "Denver Nuggets": "DEN",
    "Nuggets": "DEN",
    "Detroit Pistons": "DET",
    "Golden State Warriors": "GS",
    "Houston Rockets": "HOU",
    "Indiana Pacers": "IND",
    "Los Angeles Clippers": "LAC",
    "LA Clippers": "LAC",
    "Los Angeles Lakers": "LAL",
    "LA Lakers": "LAL",
    "Memphis Grizzlies": "MEM",
    "Miami Heat": "MIA",
    "Milwaukee Bucks": "MIL",
    "Minnesota Timberwolves": "MIN",
    "New Orleans Pelicans": "NO",
    "New York Knicks": "NY",
    "Oklahoma City Thunder": "OKC",
    "Orlando Magic": "ORL",
    "Philadelphia 76ers": "PHI",
    "Phoenix Suns": "PHX",
    "Portland Trail Blazers": "POR",
    "Sacramento Kings": "SAC",
    "San Antonio Spurs": "SA",
    "Toronto Raptors": "TOR",
    "Utah Jazz": "UTAH",
    "Washington Wizards": "WSH",
  },

  soccer_epl: {
    "Arsenal": "ARS",
    "Aston Villa": "AVL",
    "Bournemouth": "BOU",
    "AFC Bournemouth": "BOU",
    "Brentford": "BRE",
    "Brighton and Hove Albion": "BHA",
    "Brighton & Hove Albion": "BHA",
    "Brighton": "BHA",
    "Chelsea": "CHE",
    "Crystal Palace": "CRY",
    "Everton": "EVE",
    "Fulham": "FUL",
    "Ipswich Town": "IPS",
    "Ipswich": "IPS",
    "Leicester City": "LEI",
    "Leicester": "LEI",
    "Liverpool": "LIV",
    "Manchester City": "MNC",
    "Man City": "MNC",
    "Manchester United": "MAN",
    "Man United": "MAN",
    "Man Utd": "MAN",
    "Newcastle United": "NEW",
    "Newcastle": "NEW",
    "Nottingham Forest": "NFO",
    "Nott'm Forest": "NFO",
    "Southampton": "SOU",
    "Tottenham Hotspur": "TOT",
    "Spurs": "TOT",
    "West Ham United": "WHU",
    "West Ham": "WHU",
    "Wolverhampton Wanderers": "WOL",
    "Wolves": "WOL",
    "Sunderland": "SUN",
    "Leeds United": "LEE",
    "Burnley": "BUR",
    "Luton Town": "LUT",
    "Sheffield United": "SHU",
  },

  soccer_spain_la_liga: {
    "Atletico Madrid": "ATM",
    "Atlético Madrid": "ATM",
    "Atletico de Madrid": "ATM",
    "Barcelona": "BAR",
    "FC Barcelona": "BAR",
    "Real Madrid": "RMA",
    "Sevilla": "SEV",
    "FC Sevilla": "SEV",
    "Real Sociedad": "RSO",
    "Villarreal": "VIL",
    "Athletic Club": "ATH",
    "Athletic Club Bilbao": "ATH",
    "Athletic Bilbao": "ATH",
    "Valencia": "VAL",
    "Valencia CF": "VAL",
    "Osasuna": "OSA",
    "CA Osasuna": "OSA",
    "Getafe": "GET",
    "Getafe CF": "GET",
    "Celta Vigo": "CEL",
    "Celta de Vigo": "CEL",
    "Rayo Vallecano": "RAY",
    "Mallorca": "MLL",
    "RCD Mallorca": "MLL",
    "Girona": "GIR",
    "Girona FC": "GIR",
    "Las Palmas": "LPA",
    "UD Las Palmas": "LPA",
    "Alaves": "ALA",
    "Alavés": "ALA",
    "Deportivo Alaves": "ALA",
    "Deportivo Alavés": "ALA",
    "Leganes": "LEG",
    "CD Leganes": "LEG",
    "Espanyol": "ESP",
    "RCD Espanyol": "ESP",
    "Real Betis": "BET",
    "Betis": "BET",
    "Valladolid": "VLL",
    "Real Valladolid": "VLL",
  },

  soccer_germany_bundesliga: {
    "Bayern Munich": "MUN",
    "FC Bayern Munich": "MUN",
    "FC Bayern München": "MUN",
    "Borussia Dortmund": "DOR",
    "BVB Dortmund": "DOR",
    "BVB": "DOR",
    "Bayer Leverkusen": "B04",
    "Bayer 04 Leverkusen": "B04",
    "RB Leipzig": "RBL",
    "Eintracht Frankfurt": "SGE",
    "Frankfurt": "SGE",
    "VfL Wolfsburg": "WOB",
    "Wolfsburg": "WOB",
    "Borussia Monchengladbach": "BMG",
    "Borussia Mönchengladbach": "BMG",
    "Borussia M'gladbach": "BMG",
    "Gladbach": "BMG",
    "Werder Bremen": "SVW",
    "SV Werder Bremen": "SVW",
    "SC Freiburg": "SCF",
    "Freiburg": "SCF",
    "1. FC Union Berlin": "FCU",
    "FC Union Berlin": "FCU",
    "Union Berlin": "FCU",
    "VfB Stuttgart": "VFB",
    "Stuttgart": "VFB",
    "TSG Hoffenheim": "TSG",
    "Hoffenheim": "TSG",
    "1899 Hoffenheim": "TSG",
    "FC Augsburg": "FCA",
    "Augsburg": "FCA",
    "1. FSV Mainz 05": "M05",
    "Mainz 05": "M05",
    "Mainz": "M05",
    "1. FC Heidenheim": "HDH",
    "1. FC Heidenheim 1846": "HDH",
    "Heidenheim": "HDH",
    "FC Heidenheim": "HDH",
    "Holstein Kiel": "KIE",
    "Kiel": "KIE",
    "FC St. Pauli": "STP",
    "St. Pauli": "STP",
    "St Pauli": "STP",
    "VfL Bochum": "BOC",
    "Bochum": "BOC",
    "Hamburger SV": "HSV",
    "Hamburg SV": "HSV",
    "Hamburg": "HSV",
    "1. FC Köln": "KOE",
    "FC Köln": "KOE",
    "FC Cologne": "KOE",
    "Cologne": "KOE",
  },

  soccer_italy_serie_a: {
    "Juventus": "JUV",
    "AC Milan": "MIL",
    "Milan": "MIL",
    "Inter Milan": "INT",
    "Internazionale": "INT",
    "Inter": "INT",
    "Napoli": "NAP",
    "SSC Napoli": "NAP",
    "AS Roma": "ROMA",
    "Roma": "ROMA",
    "SS Lazio": "LAZ",
    "Lazio": "LAZ",
    "Atalanta": "ATA",
    "Atalanta BC": "ATA",
    "ACF Fiorentina": "FIO",
    "Fiorentina": "FIO",
    "Bologna": "BOL",
    "Bologna FC": "BOL",
    "Torino": "TOR",
    "Torino FC": "TOR",
    "Udinese": "UDI",
    "Udinese Calcio": "UDI",
    "Empoli": "EMP",
    "Cagliari": "CAG",
    "Hellas Verona": "VER",
    "Verona": "VER",
    "Lecce": "LEC",
    "US Lecce": "LEC",
    "Monza": "MON",
    "AC Monza": "MON",
    "Parma": "PAR",
    "Parma Calcio": "PAR",
    "Venezia": "VEN",
    "Venezia FC": "VEN",
    "Como": "COMO",
    "Como 1907": "COMO",
    "Genoa": "GEN",
    "Genoa CFC": "GEN",
    "Sassuolo": "SAS",
    "US Sassuolo": "SAS",
    "Salernitana": "SAL",
    "Frosinone": "FRO",
  },

  // Coppa Italia reuses the Italian club abbreviations from Serie A (ESPN uses the
  // same abbreviations across competitions). Serie B clubs that enter in earlier
  // rounds fall through to fuzzy matching.
  soccer_italy_coppa_italia: {
    "Juventus": "JUV",
    "AC Milan": "MIL",
    "Milan": "MIL",
    "Inter Milan": "INT",
    "Internazionale": "INT",
    "Inter": "INT",
    "Napoli": "NAP",
    "SSC Napoli": "NAP",
    "AS Roma": "ROMA",
    "Roma": "ROMA",
    "SS Lazio": "LAZ",
    "Lazio": "LAZ",
    "Atalanta": "ATA",
    "Atalanta BC": "ATA",
    "ACF Fiorentina": "FIO",
    "Fiorentina": "FIO",
    "Bologna": "BOL",
    "Bologna FC": "BOL",
    "Torino": "TOR",
    "Torino FC": "TOR",
    "Udinese": "UDI",
    "Udinese Calcio": "UDI",
    "Empoli": "EMP",
    "Cagliari": "CAG",
    "Hellas Verona": "VER",
    "Verona": "VER",
    "Lecce": "LEC",
    "US Lecce": "LEC",
    "Monza": "MON",
    "AC Monza": "MON",
    "Parma": "PAR",
    "Parma Calcio": "PAR",
    "Venezia": "VEN",
    "Venezia FC": "VEN",
    "Como": "COMO",
    "Como 1907": "COMO",
    "Genoa": "GEN",
    "Genoa CFC": "GEN",
    "Sassuolo": "SAS",
    "US Sassuolo": "SAS",
    "Salernitana": "SAL",
    "Frosinone": "FRO",
  },

  soccer_netherlands_eredivisie: {
    "Ajax": "AJA",
    "AFC Ajax": "AJA",
    "PSV Eindhoven": "PSV",
    "PSV": "PSV",
    "Feyenoord": "FEY",
    "Feyenoord Rotterdam": "FEY",
    "AZ Alkmaar": "AZ",
    "AZ": "AZ",
    "FC Utrecht": "UTR",
    "Utrecht": "UTR",
    "SC Twente": "TWE",
    "FC Twente": "TWE",
    "Twente": "TWE",
    "FC Groningen": "GRO",
    "Groningen": "GRO",
    "sc Heerenveen": "HEE",
    "Heerenveen": "HEE",
    "NEC Nijmegen": "NEC",
    "NEC": "NEC",
    "Almere City": "ALM",
    "Almere City FC": "ALM",
    "RKC Waalwijk": "RKC",
    "NAC Breda": "NAC",
    "PEC Zwolle": "PEC",
    "Zwolle": "PEC",
    "Sparta Rotterdam": "SPA",
    "Sparta": "SPA",
    "Go Ahead Eagles": "GAE",
    "Willem II": "WIL",
    "Heracles": "HER",
    "Heracles Almelo": "HER",
    "Vitesse": "VIT",
    "SBV Vitesse": "VIT",
    "Excelsior": "EXC",
    "Fortuna Sittard": "FOR",
    "FC Volendam": "VOL",
  },

  soccer_france_ligue_one: {
    "Paris Saint-Germain": "PSG",
    "Paris SG": "PSG",
    "PSG": "PSG",
    "Olympique de Marseille": "OLM",
    "Marseille": "OLM",
    "Olympique Lyonnais": "LYON",
    "Lyon": "LYON",
    "AS Monaco": "MON",
    "Monaco": "MON",
    "LOSC Lille": "LILL",
    "Lille": "LILL",
    "Stade Rennais": "REN",
    "Rennes": "REN",
    "RC Lens": "RCL",
    "Lens": "RCL",
    "OGC Nice": "NICE",
    "Nice": "NICE",
    "Stade de Reims": "REI",
    "Reims": "REI",
    "Montpellier HSC": "MHSC",
    "Montpellier": "MHSC",
    "RC Strasbourg": "STR",
    "Strasbourg": "STR",
    "FC Nantes": "NAN",
    "Nantes": "NAN",
    "AJ Auxerre": "AUX",
    "Auxerre": "AUX",
    "Stade Brest 29": "BRE",
    "Brest": "BRE",
    "Toulouse FC": "TOU",
    "Toulouse": "TOU",
    "Le Havre AC": "HAC",
    "Le Havre": "HAC",
    "Angers SCO": "ANG",
    "Angers": "ANG",
    "AS Saint-Etienne": "STE",
    "Saint-Etienne": "STE",
    "FC Lorient": "LOR",
    "Lorient": "LOR",
    "Metz": "METZ",
    "FC Metz": "METZ",
    "Paris FC": "PAR",
  },

  soccer_brazil_campeonato: {
    "Athletico Paranaense": "CAP",
    "Atletico Paranaense": "CAP",
    "Athletico-PR": "CAP",
    "Atletico Mineiro": "CAM",
    "Atlético Mineiro": "CAM",
    "Atlético-MG": "CAM",
    "Bahia": "BAH",
    "Botafogo": "BOT",
    "Chapecoense": "CHA",
    "Corinthians": "COR",
    "Coritiba": "CFC",
    "Cruzeiro": "CRU",
    "Flamengo": "FLA",
    "Fluminense": "FLU",
    "Gremio": "GRE",
    "Grêmio": "GRE",
    "Internacional": "INT",
    "Mirassol": "MIR",
    "Palmeiras": "PAL",
    "Red Bull Bragantino": "BRA",
    "Bragantino": "BRA",
    "Bragantino-SP": "BRA",
    "Remo": "REMO",
    "Santos": "SAN",
    "Sao Paulo": "SAO",
    "São Paulo": "SAO",
    "Vasco da Gama": "VAS",
    "Vasco Da Gama": "VAS",
    "Vitoria": "VIT",
    "Vitória": "VIT",
  },

  icehockey_nhl: {
    "Anaheim Ducks": "ANA",
    "Boston Bruins": "BOS",
    "Buffalo Sabres": "BUF",
    "Calgary Flames": "CGY",
    "Carolina Hurricanes": "CAR",
    "Chicago Blackhawks": "CHI",
    "Colorado Avalanche": "COL",
    "Columbus Blue Jackets": "CBJ",
    "Dallas Stars": "DAL",
    "Detroit Red Wings": "DET",
    "Edmonton Oilers": "EDM",
    "Florida Panthers": "FLA",
    "Los Angeles Kings": "LA",
    "Minnesota Wild": "MIN",
    "Montreal Canadiens": "MTL",
    "Nashville Predators": "NSH",
    "New Jersey Devils": "NJ",
    "New York Islanders": "NYI",
    "New York Rangers": "NYR",
    "Ottawa Senators": "OTT",
    "Philadelphia Flyers": "PHI",
    "Pittsburgh Penguins": "PIT",
    "San Jose Sharks": "SJ",
    "Seattle Kraken": "SEA",
    "St. Louis Blues": "STL",
    "St Louis Blues": "STL",
    "Tampa Bay Lightning": "TB",
    "Toronto Maple Leafs": "TOR",
    "Utah Mammoth": "UTAH",
    "Utah Hockey Club": "UTAH",
    "Vancouver Canucks": "VAN",
    "Vegas Golden Knights": "VGK",
    "Washington Capitals": "WSH",
    "Winnipeg Jets": "WPG",
  },

  // UCL: only clubs with Odds API ↔ ESPN name divergence that fuzzy can't resolve.
  // Regular clubs (Arsenal, Real Madrid, Bayern, etc.) fall through to fuzzy matching fine.
  soccer_uefa_champs_league: {
    "Sporting Lisbon": "SCP",
    "Sporting CP": "SCP",
    "Man City": "MNC",
    "Manchester City": "MNC",
    "Man United": "MAN",
    "Manchester United": "MAN",
    "Bayern Munich": "MUN",
    "FC Bayern Munich": "MUN",
  },

  soccer_uefa_europa_league: {
    "Sporting Lisbon": "SCP",
    "Sporting CP": "SCP",
    "Man United": "MAN",
    "Manchester United": "MAN",
    "Man City": "MNC",
    "Manchester City": "MNC",
  },

  soccer_uefa_europa_conference_league: {
    "Man United": "MAN",
    "Manchester United": "MAN",
  },

  // Copa Libertadores: only clubs with known Odds API ↔ ESPN name divergence.
  // Most club names are close enough for fuzzy matching (0.65 threshold).
  soccer_conmebol_copa_libertadores: {
    "Flamengo": "FLA",
    "CR Flamengo": "FLA",
    "Fluminense": "FLU",
    "Fluminense FC": "FLU",
    "Palmeiras": "PAL",
    "SE Palmeiras": "PAL",
    "Boca Juniors": "CABJ",
    "CA Boca Juniors": "CABJ",
    "Nacional": "NAC",
    "Club Nacional": "NAC",
    "Penarol": "PEN",
    "Club Atletico Penarol": "PEN",
    "Peñarol": "PEN",
    "Independiente del Valle": "IDV",
    "LDU Quito": "LDU",
    "Liga de Quito": "LDU",
    "UCV FC": "UCV",
    "Universidad Central": "UCV",
    "Libertad Asuncion": "LIB",
    "Libertad": "LIB",
    "Mirassol": "MIR",
    "Lanus": "LAN",
    "Lanús": "LAN",
    "Rosario Central": "ROS",
  },

  // World Cup: only entries where Odds API name diverges from ESPN displayName.
  // Most country names match between the two systems; only exceptions listed here.
  soccer_fifa_world_cup: {
    "USA": "USA",
    "United States": "USA",
  },

  soccer_fifa_world_cup_qualifiers_europe: {
    "USA": "USA",
    "United States": "USA",
  },
};
